(function(){'use strict';
const $=id=>document.getElementById(id);
const state={base:null,updated:null,baseName:'base.geojson',updatedName:'actualizada.geojson',baseFeatures:[],updatedFeatures:[],key:'',keyOptions:[],results:[],duplicateBase:0,duplicateUpdated:0};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const jsonStable=value=>{if(value===undefined)return 'undefined';if(value===null||typeof value!=='object')return JSON.stringify(value);if(Array.isArray(value))return '['+value.map(jsonStable).join(',')+']';return '{'+Object.keys(value).sort().map(k=>JSON.stringify(k)+':'+jsonStable(value[k])).join(',')+'}'};
function featuresOf(obj){if(obj?.type==='FeatureCollection')return Array.isArray(obj.features)?obj.features:[];if(obj?.type==='Feature')return[obj];if(obj?.type&&obj.coordinates)return[{type:'Feature',geometry:obj,properties:{}}];if(Array.isArray(obj))return obj.map((x,i)=>x?.type==='Feature'?x:{type:'Feature',geometry:null,properties:{...x,__row:i+1}});if(Array.isArray(obj?.data))return featuresOf(obj.data);throw Error('El JSON no contiene una FeatureCollection, Feature o geometría GeoJSON válida.')} 
function candidateKeys(){const set=new Set([...state.baseFeatures,...state.updatedFeatures].flatMap(f=>Object.keys(f?.properties||{})));const preferred=['id','ID','fid','gid','codigo','code','uuid','nombre','name'];return preferred.filter(k=>set.has(k)).concat([...set].filter(k=>!preferred.includes(k)).sort((a,b)=>a.localeCompare(b,'es')))}
function rawKey(feature,key,index){if(key==='__index')return`fila-${index+1}`;const value=feature?.properties?.[key];return value===undefined||value===null||value===''?`sin-valor-${index+1}`:String(value)}
function groups(features,key){const map=new Map();let duplicates=0;features.forEach((feature,index)=>{const k=rawKey(feature,key,index);if(map.has(k))duplicates++;if(!map.has(k))map.set(k,[]);map.get(k).push({feature,index})});return{map,duplicates}}
function changedFields(a,b){const ak=Object.keys(a||{}),bk=Object.keys(b||{}),keys=[...new Set([...ak,...bk])];return keys.filter(k=>jsonStable(a?.[k])!==jsonStable(b?.[k])).sort((x,y)=>x.localeCompare(y,'es'))}
function diff(){const base=groups(state.baseFeatures,state.key),updated=groups(state.updatedFeatures,state.key);state.duplicateBase=base.duplicates;state.duplicateUpdated=updated.duplicates;const keys=[...new Set([...base.map.keys(),...updated.map.keys()])].sort((a,b)=>a.localeCompare(b,'es',{numeric:true}));state.results=[];keys.forEach(key=>{const a=base.map.get(key)||[],b=updated.map.get(key)||[],n=Math.max(a.length,b.length);for(let i=0;i<n;i++){const left=a[i]?.feature,right=b[i]?.feature;let status='unchanged',geometryChanged=false,propertyChanged=false,fields=[];if(!left)status='added';else if(!right)status='removed';else{geometryChanged=jsonStable(left.geometry)!==jsonStable(right.geometry);fields=changedFields(left.properties,right.properties);propertyChanged=fields.length>0;if(geometryChanged||propertyChanged)status='changed'}state.results.push({key:key+(n>1?` · #${i+1}`:''),rawKey:key,status,base:left,updated:right,geometryChanged,propertyChanged,fields})}});render()}
function setFile(kind,obj,name){state[kind]=obj;state[kind+'Name']=name;state[kind+'Features']=featuresOf(obj);$(kind+'-name').textContent=`${name} · ${state[kind+'Features'].length} entidades`;if(state.baseFeatures.length&&state.updatedFeatures.length){$('workspace').classList.remove('hidden');setupKeys();$('status').textContent='Las dos versiones están cargadas. Revisa la clave y audita los resultados.';$('status').className='status good'}else{$('status').textContent=`${kind==='base'?'Base':'Actualizada'} cargada. Falta la otra versión.`;$('status').className='status'}}
function setupKeys(){const keys=candidateKeys();state.keyOptions=[...keys,'__index'];const old=state.key;state.key=keys[0]||'__index';$('key').innerHTML=state.keyOptions.map(k=>`<option value="${esc(k)}">${k==='__index'?'Índice de fila (no estable)':esc(k)}</option>`).join('');if(state.keyOptions.includes(old))state.key=old;$('key').value=state.key;diff()}
function label(status){return{added:'Nueva',removed:'Eliminada',changed:'Modificada',unchanged:'Sin cambios'}[status]}
function detail(r){if(r.status==='added')return'Nueva entidad en la versión actualizada';if(r.status==='removed')return'Ya no aparece en la versión actualizada';if(r.status==='unchanged')return'Geometría y atributos sin diferencias';const bits=[];if(r.geometryChanged)bits.push('geometría');if(r.propertyChanged)bits.push(`atributos: ${r.fields.slice(0,4).join(', ')}${r.fields.length>4?'…':''}`);return bits.join(' · ')}
function visible(){const q=$('query').value.trim().toLocaleLowerCase('es'),filter=$('filter').value;return state.results.filter(r=>(filter==='all'||r.status===filter)&&(!q||`${r.key} ${jsonStable(r.updated?.properties||r.base?.properties||{})}`.toLocaleLowerCase('es').includes(q)))}
function render(){const totals={added:0,removed:0,changed:0,unchanged:0};state.results.forEach(r=>totals[r.status]++);Object.entries(totals).forEach(([k,v])=>$(k==='unchanged'?'same':k).textContent=v);const rows=visible(),limit=500;$('result-count').textContent=`${rows.length} de ${state.results.length} resultados`;$('rows').innerHTML=rows.slice(0,limit).map(r=>{const f=r.updated||r.base;const name=f?.properties?.nombre??f?.properties?.name??f?.properties?.titulo??'—';return`<tr><td><span class="badge ${r.status}">${label(r.status)}</span></td><td><code>${esc(r.key)}</code></td><td class="detail">${esc(detail(r))}${r.fields.length?`<small>${r.fields.map(esc).join(', ')}</small>`:''}</td><td>${esc(name)}<small class="muted">${r.updated?'versión actual':'solo en base'}</small></td></tr>`}).join('')||'<tr><td colspan="4" class="muted">No hay resultados para este filtro.</td></tr>';$('table-note').textContent=rows.length>limit?`Se muestran ${limit} filas. Exporta para conservar el detalle completo.`:'';const warnings=[];if(state.key==='__index')warnings.push('La comparación usa el índice de fila: si se reordenan las entidades, aparecerán cambios aunque representen el mismo elemento.');if(state.duplicateBase||state.duplicateUpdated)warnings.push(`Hay claves repetidas: base ${state.duplicateBase}, actualizada ${state.duplicateUpdated}. Se emparejan por orden de aparición.`);$('warning').textContent=warnings.join(' ');$('warning').classList.toggle('hidden',!warnings.length);$('key-note').textContent=state.key==='__index'?'Clave provisional':'Clave seleccionada';$('preview').textContent=JSON.stringify({base:state.baseName,updated:state.updatedName,key:state.key,summary:totals},null,2)}
function report(){const totals={added:0,removed:0,changed:0,unchanged:0};state.results.forEach(r=>totals[r.status]++);return{tool:'Layer Diff',version:1,generatedAt:new Date().toISOString(),base:state.baseName,updated:state.updatedName,key:state.key,summary:totals,warnings:{duplicateBase:state.duplicateBase,duplicateUpdated:state.duplicateUpdated,indexKey:state.key==='__index'},changes:state.results.map(r=>({key:r.key,status:r.status,geometryChanged:r.geometryChanged,propertyChanged:r.propertyChanged,changedProperties:r.fields,baseFeature:r.base||null,updatedFeature:r.updated||null}))}}
function csv(){const head=['estado','clave','geometria_cambiada','atributos_cambiados','campos_cambiados','nombre','version'];const lines=[head,...state.results.map(r=>{const f=r.updated||r.base;return[r.status,r.key,r.geometryChanged?'si':'no',r.propertyChanged?'si':'no',r.fields.join('|'),f?.properties?.nombre??f?.properties?.name??'',r.updated?'actualizada':'base']})];return lines.map(row=>row.map(x=>`"${String(x??'').replace(/"/g,'""')}"`).join(',')).join('\n')+'\n'}
function delta(){const features=state.results.filter(r=>r.status==='added'||r.status==='changed').map(r=>{const f=JSON.parse(JSON.stringify(r.updated));f.properties={...(f.properties||{}),__layer_diff:r.status,__layer_diff_key:r.key};return f});return{type:'FeatureCollection',name:'layer-diff-delta',features}}
function download(name,data,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
async function read(kind,file){try{setFile(kind,JSON.parse(await file.text()),file.name)}catch(e){$('status').textContent=e.message;$('status').className='status error'}}
function demo(){setFile('base',{type:'FeatureCollection',features:[{type:'Feature',geometry:{type:'Point',coordinates:[-3.704,40.417]},properties:{id:'A-01',nombre:'Recinto norte',periodo:'romano',fuente:'inventario 2025'}},{type:'Feature',geometry:{type:'Point',coordinates:[-3.69,40.42]},properties:{id:'A-02',nombre:'Camino antiguo',periodo:'medieval',fuente:'inventario 2025'}},{type:'Feature',geometry:{type:'Point',coordinates:[-3.71,40.41]},properties:{id:'A-03',nombre:'Cantera',periodo:'moderno',fuente:'inventario 2025'}}]},'inventario-2025.geojson');setFile('updated',{type:'FeatureCollection',features:[{type:'Feature',geometry:{type:'Point',coordinates:[-3.704,40.417]},properties:{id:'A-01',nombre:'Recinto norte',periodo:'romano',fuente:'inventario 2026'}},{type:'Feature',geometry:{type:'Point',coordinates:[-3.69,40.421]},properties:{id:'A-02',nombre:'Camino antiguo',periodo:'medieval',fuente:'inventario 2026'}},{type:'Feature',geometry:{type:'Point',coordinates:[-3.70,40.40]},properties:{id:'A-04',nombre:'Taller nuevo',periodo:'contemporáneo',fuente:'inventario 2026'}}]},'inventario-2026.geojson')}
function clear(){state.base=null;state.updated=null;state.baseFeatures=[];state.updatedFeatures=[];state.results=[];$('base-name').textContent='Sin archivo';$('updated-name').textContent='Sin archivo';$('base-file').value='';$('updated-file').value='';$('workspace').classList.add('hidden');$('status').textContent='Carga ambas versiones para empezar.';$('status').className='status'}
$('base-file').addEventListener('change',e=>e.target.files[0]&&read('base',e.target.files[0]));$('updated-file').addEventListener('change',e=>e.target.files[0]&&read('updated',e.target.files[0]));$('demo').addEventListener('click',demo);$('clear').addEventListener('click',clear);$('key').addEventListener('change',e=>{state.key=e.target.value;diff()});$('query').addEventListener('input',render);$('filter').addEventListener('change',render);$('json').addEventListener('click',()=>download('layer-diff-report.json',JSON.stringify(report(),null,2),'application/json'));$('csv').addEventListener('click',()=>download('layer-diff-report.csv',csv(),'text/csv;charset=utf-8'));$('geojson').addEventListener('click',()=>download('layer-diff-delta.geojson',JSON.stringify(delta(),null,2),'application/geo+json'));$('workspace').addEventListener('keydown',e=>{if(e.key==='Escape')$('query').value=''})
})();
